#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
# Requirements:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
#+ using curl, it must return a page that contains the string Hello World


sudo apt-get update
sudo apt-get -y install nginx
sudo 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
