#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo mkdir /var/www/html/
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {
        listen 80;
        listen [::]:80;
        root /var/www/html;
        index index.html index.htm;

	location /redirect_me {
		return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
" | sudo tee /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
