#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
#+ contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
        listen 80;
        listen [::]:80;
        root /var/www/html;
        index index.html index.htm;

        location /redirect_me {
                return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal
}
" | sudo tee /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
