#!/usr/bin/env bash
# Update the package list and install HAProxy

sudo apt-get -y update
sudo apt-get install -y haproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	timeout	connect	5000
	timeout	client	50000
	timeout	server	50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server server1 100.26.168.29:80 check
	server server2 54.173.39.101:80 check
EOF

sudo systemctl enable haproxy
sudo systemctl restart haproxy
