#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
hour=0
minutes=1
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $minutes -le 59 ]; do
		echo "$minutes"
		((minutes++))
	done
	minutes=1
	((hour++))
done
